### ISSUE TITLE
Rollback function to earlier versions

### ISSUE THREAD

**Issue by levisingularity** [singnet/das-servless-functions#31]

**Comment by levisingularity** [comment]
- [ ] Change the pipeline to version docker images
- [ ] Rollback function to the last stable version

**Comment by levisingularity** [comment]
![Image](https://github.com/singnet/das-servless-functions/assets/141682181/74b96fdd-4ae6-4f60-ae71-bde5a742df67)


Now, we have the flexibility to revert to a previous version effortlessly. By simply modifying the 'das-function.yml' file within the 'das-infra-stack-vultr' repository and pushing it to either the 'develop' or 'master' branch, we can initiate this process. Once the changes are pushed to 'develop', they'll be deployed to the development environment. Similarly, when updates are pushed to 'master', the changes will be mirrored in the production environment.

Imagine you have an existing function represented by an image tagged as `trueagi/das:v1.0.0-queryengine`. You're planning an upgrade to a newer version `v1.1.0-queryengine`, which has been built and pushed to Docker Hub from the 'das-serverless-function' repository. To execute this upgrade, you'll modify the 'das-function.yml' file in your GitHub repository, specifying the updated image version. Once done, you'll push these changes to GitHub and merge them into either the 'develop' or 'master' branch, based on your target environment.

Here's a sample structure of the 'das-function.yml' file:

```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8081
functions:
  atomdb:
    lang: python3-http
    image: trueagi/das:v1.0.0-queryengine
    environment:
      read_timeout: 300s
      write_timeout: 300s
      exec_timeout: 300s
```

In case a rollback is needed, there are two approaches: first, you can execute the `git revert` command to revert to the previous commit, effectively rolling back the changes. Alternatively, you can manually adjust the 'das-function.yml' file, reverting the image version to the desired previous state. Once this adjustment is made, push it back to the repository, and your function will return to its previous state.
